/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jcm_discordgamesdk_NetworkManager */

#ifndef _Included_de_jcm_discordgamesdk_NetworkManager
#define _Included_de_jcm_discordgamesdk_NetworkManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jcm_discordgamesdk_NetworkManager
 * Method:    getPeerId
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_jcm_discordgamesdk_NetworkManager_getPeerId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jcm_discordgamesdk_NetworkManager
 * Method:    flush
 * Signature: (J)Lde/jcm/discordgamesdk/Result;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_NetworkManager_flush
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jcm_discordgamesdk_NetworkManager
 * Method:    openPeer
 * Signature: (JJLjava/lang/String;)Lde/jcm/discordgamesdk/Result;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_NetworkManager_openPeer
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     de_jcm_discordgamesdk_NetworkManager
 * Method:    updatePeer
 * Signature: (JJLjava/lang/String;)Lde/jcm/discordgamesdk/Result;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_NetworkManager_updatePeer
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     de_jcm_discordgamesdk_NetworkManager
 * Method:    closePeer
 * Signature: (JJ)Lde/jcm/discordgamesdk/Result;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_NetworkManager_closePeer
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_jcm_discordgamesdk_NetworkManager
 * Method:    openChannel
 * Signature: (JJBZ)Lde/jcm/discordgamesdk/Result;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_NetworkManager_openChannel
  (JNIEnv *, jobject, jlong, jlong, jbyte, jboolean);

/*
 * Class:     de_jcm_discordgamesdk_NetworkManager
 * Method:    closeChannel
 * Signature: (JJB)Lde/jcm/discordgamesdk/Result;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_NetworkManager_closeChannel
  (JNIEnv *, jobject, jlong, jlong, jbyte);

/*
 * Class:     de_jcm_discordgamesdk_NetworkManager
 * Method:    sendMessage
 * Signature: (JJB[BII)Lde/jcm/discordgamesdk/Result;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_NetworkManager_sendMessage
  (JNIEnv *, jobject, jlong, jlong, jbyte, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
