/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jcm_discordgamesdk_ImageManager */

#ifndef _Included_de_jcm_discordgamesdk_ImageManager
#define _Included_de_jcm_discordgamesdk_ImageManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jcm_discordgamesdk_ImageManager
 * Method:    fetch
 * Signature: (JIJIZLjava/util/function/BiConsumer;)V
 */
JNIEXPORT void JNICALL Java_de_jcm_discordgamesdk_ImageManager_fetch
  (JNIEnv *, jobject, jlong, jint, jlong, jint, jboolean, jobject);

/*
 * Class:     de_jcm_discordgamesdk_ImageManager
 * Method:    getDimensions
 * Signature: (JIJI)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_ImageManager_getDimensions
  (JNIEnv *, jobject, jlong, jint, jlong, jint);

/*
 * Class:     de_jcm_discordgamesdk_ImageManager
 * Method:    getData
 * Signature: (JIJII)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_ImageManager_getData
  (JNIEnv *, jobject, jlong, jint, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
