/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jcm_discordgamesdk_ActivityManager */

#ifndef _Included_de_jcm_discordgamesdk_ActivityManager
#define _Included_de_jcm_discordgamesdk_ActivityManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jcm_discordgamesdk_ActivityManager
 * Method:    updateActivity
 * Signature: (JJLjava/util/function/Consumer;)V
 */
JNIEXPORT void JNICALL Java_de_jcm_discordgamesdk_ActivityManager_updateActivity
  (JNIEnv *, jobject, jlong, jlong, jobject);

/*
 * Class:     de_jcm_discordgamesdk_ActivityManager
 * Method:    clearActivity
 * Signature: (JLjava/util/function/Consumer;)V
 */
JNIEXPORT void JNICALL Java_de_jcm_discordgamesdk_ActivityManager_clearActivity
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     de_jcm_discordgamesdk_ActivityManager
 * Method:    sendRequestReply
 * Signature: (JJILjava/util/function/Consumer;)V
 */
JNIEXPORT void JNICALL Java_de_jcm_discordgamesdk_ActivityManager_sendRequestReply
  (JNIEnv *, jobject, jlong, jlong, jint, jobject);

/*
 * Class:     de_jcm_discordgamesdk_ActivityManager
 * Method:    sendInvite
 * Signature: (JJILjava/lang/String;Ljava/util/function/Consumer;)V
 */
JNIEXPORT void JNICALL Java_de_jcm_discordgamesdk_ActivityManager_sendInvite
  (JNIEnv *, jobject, jlong, jlong, jint, jstring, jobject);

/*
 * Class:     de_jcm_discordgamesdk_ActivityManager
 * Method:    acceptRequest
 * Signature: (JJLjava/util/function/Consumer;)V
 */
JNIEXPORT void JNICALL Java_de_jcm_discordgamesdk_ActivityManager_acceptRequest
  (JNIEnv *, jobject, jlong, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
