/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jcm_discordgamesdk_activity_ActivitySecrets */

#ifndef _Included_de_jcm_discordgamesdk_activity_ActivitySecrets
#define _Included_de_jcm_discordgamesdk_activity_ActivitySecrets
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jcm_discordgamesdk_activity_ActivitySecrets
 * Method:    setMatchSecret
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_jcm_discordgamesdk_activity_ActivitySecrets_setMatchSecret
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     de_jcm_discordgamesdk_activity_ActivitySecrets
 * Method:    getMatchSecret
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_jcm_discordgamesdk_activity_ActivitySecrets_getMatchSecret
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jcm_discordgamesdk_activity_ActivitySecrets
 * Method:    setJoinSecret
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_jcm_discordgamesdk_activity_ActivitySecrets_setJoinSecret
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     de_jcm_discordgamesdk_activity_ActivitySecrets
 * Method:    getJoinSecret
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_jcm_discordgamesdk_activity_ActivitySecrets_getJoinSecret
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jcm_discordgamesdk_activity_ActivitySecrets
 * Method:    setSpectateSecret
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_jcm_discordgamesdk_activity_ActivitySecrets_setSpectateSecret
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     de_jcm_discordgamesdk_activity_ActivitySecrets
 * Method:    getSpectateSecret
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_jcm_discordgamesdk_activity_ActivitySecrets_getSpectateSecret
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
