/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jcm_discordgamesdk_activity_Activity */

#ifndef _Included_de_jcm_discordgamesdk_activity_Activity
#define _Included_de_jcm_discordgamesdk_activity_Activity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jcm_discordgamesdk_activity_Activity
 * Method:    allocate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_jcm_discordgamesdk_activity_Activity_allocate
  (JNIEnv *, jobject);

/*
 * Class:     de_jcm_discordgamesdk_activity_Activity
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_jcm_discordgamesdk_activity_Activity_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jcm_discordgamesdk_activity_Activity
 * Method:    setState
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_jcm_discordgamesdk_activity_Activity_setState
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     de_jcm_discordgamesdk_activity_Activity
 * Method:    getState
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_jcm_discordgamesdk_activity_Activity_getState
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jcm_discordgamesdk_activity_Activity
 * Method:    setDetails
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_jcm_discordgamesdk_activity_Activity_setDetails
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     de_jcm_discordgamesdk_activity_Activity
 * Method:    getDetails
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_jcm_discordgamesdk_activity_Activity_getDetails
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jcm_discordgamesdk_activity_Activity
 * Method:    setType
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_de_jcm_discordgamesdk_activity_Activity_setType
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_jcm_discordgamesdk_activity_Activity
 * Method:    getType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_jcm_discordgamesdk_activity_Activity_getType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jcm_discordgamesdk_activity_Activity
 * Method:    getTimestamps
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_jcm_discordgamesdk_activity_Activity_getTimestamps
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jcm_discordgamesdk_activity_Activity
 * Method:    getParty
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_jcm_discordgamesdk_activity_Activity_getParty
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
