/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jcm_discordgamesdk_lobby_LobbyMemberTransaction */

#ifndef _Included_de_jcm_discordgamesdk_lobby_LobbyMemberTransaction
#define _Included_de_jcm_discordgamesdk_lobby_LobbyMemberTransaction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jcm_discordgamesdk_lobby_LobbyMemberTransaction
 * Method:    setMetadata
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Lde/jcm/discordgamesdk/Result;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_lobby_LobbyMemberTransaction_setMetadata
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     de_jcm_discordgamesdk_lobby_LobbyMemberTransaction
 * Method:    deleteMetadata
 * Signature: (JLjava/lang/String;)Lde/jcm/discordgamesdk/Result;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_lobby_LobbyMemberTransaction_deleteMetadata
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
