/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jcm_discordgamesdk_RelationshipManager */

#ifndef _Included_de_jcm_discordgamesdk_RelationshipManager
#define _Included_de_jcm_discordgamesdk_RelationshipManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jcm_discordgamesdk_RelationshipManager
 * Method:    filter
 * Signature: (JLjava/util/function/Predicate;)V
 */
JNIEXPORT void JNICALL Java_de_jcm_discordgamesdk_RelationshipManager_filter
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     de_jcm_discordgamesdk_RelationshipManager
 * Method:    count
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_RelationshipManager_count
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jcm_discordgamesdk_RelationshipManager
 * Method:    get
 * Signature: (JJ)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_RelationshipManager_get
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_jcm_discordgamesdk_RelationshipManager
 * Method:    getAt
 * Signature: (JI)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_RelationshipManager_getAt
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
