/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jcm_discordgamesdk_CreateParams */

#ifndef _Included_de_jcm_discordgamesdk_CreateParams
#define _Included_de_jcm_discordgamesdk_CreateParams
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jcm_discordgamesdk_CreateParams
 * Method:    allocate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_jcm_discordgamesdk_CreateParams_allocate
  (JNIEnv *, jobject);

/*
 * Class:     de_jcm_discordgamesdk_CreateParams
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_jcm_discordgamesdk_CreateParams_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jcm_discordgamesdk_CreateParams
 * Method:    setClientID
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_jcm_discordgamesdk_CreateParams_setClientID
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_jcm_discordgamesdk_CreateParams
 * Method:    getClientID
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_jcm_discordgamesdk_CreateParams_getClientID
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jcm_discordgamesdk_CreateParams
 * Method:    setFlags
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_jcm_discordgamesdk_CreateParams_setFlags
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_jcm_discordgamesdk_CreateParams
 * Method:    getFlags
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_jcm_discordgamesdk_CreateParams_getFlags
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jcm_discordgamesdk_CreateParams
 * Method:    getDefaultFlags
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_jcm_discordgamesdk_CreateParams_getDefaultFlags
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
