/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jcm_discordgamesdk_activity_ActivityTimestamps */

#ifndef _Included_de_jcm_discordgamesdk_activity_ActivityTimestamps
#define _Included_de_jcm_discordgamesdk_activity_ActivityTimestamps
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jcm_discordgamesdk_activity_ActivityTimestamps
 * Method:    setStart
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_jcm_discordgamesdk_activity_ActivityTimestamps_setStart
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_jcm_discordgamesdk_activity_ActivityTimestamps
 * Method:    getStart
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_jcm_discordgamesdk_activity_ActivityTimestamps_getStart
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jcm_discordgamesdk_activity_ActivityTimestamps
 * Method:    setEnd
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_jcm_discordgamesdk_activity_ActivityTimestamps_setEnd
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_jcm_discordgamesdk_activity_ActivityTimestamps
 * Method:    getEnd
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_jcm_discordgamesdk_activity_ActivityTimestamps_getEnd
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
