/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jcm_discordgamesdk_lobby_LobbySearchQuery */

#ifndef _Included_de_jcm_discordgamesdk_lobby_LobbySearchQuery
#define _Included_de_jcm_discordgamesdk_lobby_LobbySearchQuery
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jcm_discordgamesdk_lobby_LobbySearchQuery
 * Method:    filter
 * Signature: (JLjava/lang/String;IILjava/lang/String;)Lde/jcm/discordgamesdk/Result;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_lobby_LobbySearchQuery_filter
  (JNIEnv *, jobject, jlong, jstring, jint, jint, jstring);

/*
 * Class:     de_jcm_discordgamesdk_lobby_LobbySearchQuery
 * Method:    sort
 * Signature: (JLjava/lang/String;ILjava/lang/String;)Lde/jcm/discordgamesdk/Result;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_lobby_LobbySearchQuery_sort
  (JNIEnv *, jobject, jlong, jstring, jint, jstring);

/*
 * Class:     de_jcm_discordgamesdk_lobby_LobbySearchQuery
 * Method:    limit
 * Signature: (JI)Lde/jcm/discordgamesdk/Result;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_lobby_LobbySearchQuery_limit
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_jcm_discordgamesdk_lobby_LobbySearchQuery
 * Method:    distance
 * Signature: (JI)Lde/jcm/discordgamesdk/Result;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_lobby_LobbySearchQuery_distance
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
