/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jcm_discordgamesdk_lobby_LobbyTransaction */

#ifndef _Included_de_jcm_discordgamesdk_lobby_LobbyTransaction
#define _Included_de_jcm_discordgamesdk_lobby_LobbyTransaction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jcm_discordgamesdk_lobby_LobbyTransaction
 * Method:    setType
 * Signature: (JI)Lde/jcm/discordgamesdk/Result;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_lobby_LobbyTransaction_setType
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_jcm_discordgamesdk_lobby_LobbyTransaction
 * Method:    setOwner
 * Signature: (JJ)Lde/jcm/discordgamesdk/Result;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_lobby_LobbyTransaction_setOwner
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_jcm_discordgamesdk_lobby_LobbyTransaction
 * Method:    setCapacity
 * Signature: (JI)Lde/jcm/discordgamesdk/Result;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_lobby_LobbyTransaction_setCapacity
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_jcm_discordgamesdk_lobby_LobbyTransaction
 * Method:    setMetadata
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Lde/jcm/discordgamesdk/Result;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_lobby_LobbyTransaction_setMetadata
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     de_jcm_discordgamesdk_lobby_LobbyTransaction
 * Method:    deleteMetadata
 * Signature: (JLjava/lang/String;)Lde/jcm/discordgamesdk/Result;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_lobby_LobbyTransaction_deleteMetadata
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     de_jcm_discordgamesdk_lobby_LobbyTransaction
 * Method:    setLocked
 * Signature: (JZ)Lde/jcm/discordgamesdk/Result;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_lobby_LobbyTransaction_setLocked
  (JNIEnv *, jobject, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
