/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jcm_discordgamesdk_activity_ActivityParty */

#ifndef _Included_de_jcm_discordgamesdk_activity_ActivityParty
#define _Included_de_jcm_discordgamesdk_activity_ActivityParty
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jcm_discordgamesdk_activity_ActivityParty
 * Method:    setID
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_jcm_discordgamesdk_activity_ActivityParty_setID
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     de_jcm_discordgamesdk_activity_ActivityParty
 * Method:    getID
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_jcm_discordgamesdk_activity_ActivityParty_getID
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jcm_discordgamesdk_activity_ActivityParty
 * Method:    getSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_jcm_discordgamesdk_activity_ActivityParty_getSize
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
