/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jcm_discordgamesdk_VoiceManager */

#ifndef _Included_de_jcm_discordgamesdk_VoiceManager
#define _Included_de_jcm_discordgamesdk_VoiceManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jcm_discordgamesdk_VoiceManager
 * Method:    getInputMode
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_VoiceManager_getInputMode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jcm_discordgamesdk_VoiceManager
 * Method:    setInputMode
 * Signature: (JLde/jcm/discordgamesdk/voice/VoiceInputMode;Ljava/util/function/Consumer;)V
 */
JNIEXPORT void JNICALL Java_de_jcm_discordgamesdk_VoiceManager_setInputMode
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     de_jcm_discordgamesdk_VoiceManager
 * Method:    isSelfMute
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_VoiceManager_isSelfMute
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jcm_discordgamesdk_VoiceManager
 * Method:    setSelfMute
 * Signature: (JZ)Lde/jcm/discordgamesdk/Result;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_VoiceManager_setSelfMute
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     de_jcm_discordgamesdk_VoiceManager
 * Method:    isSelfDeaf
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_VoiceManager_isSelfDeaf
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jcm_discordgamesdk_VoiceManager
 * Method:    setSelfDeaf
 * Signature: (JZ)Lde/jcm/discordgamesdk/Result;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_VoiceManager_setSelfDeaf
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     de_jcm_discordgamesdk_VoiceManager
 * Method:    isLocalMute
 * Signature: (JJ)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_VoiceManager_isLocalMute
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_jcm_discordgamesdk_VoiceManager
 * Method:    setLocalMute
 * Signature: (JJZ)Lde/jcm/discordgamesdk/Result;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_VoiceManager_setLocalMute
  (JNIEnv *, jobject, jlong, jlong, jboolean);

/*
 * Class:     de_jcm_discordgamesdk_VoiceManager
 * Method:    getLocalVolume
 * Signature: (JJ)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_VoiceManager_getLocalVolume
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_jcm_discordgamesdk_VoiceManager
 * Method:    setLocalVolume
 * Signature: (JJB)Lde/jcm/discordgamesdk/Result;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_VoiceManager_setLocalVolume
  (JNIEnv *, jobject, jlong, jlong, jbyte);

#ifdef __cplusplus
}
#endif
#endif
