/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jcm_discordgamesdk_LobbyManager */

#ifndef _Included_de_jcm_discordgamesdk_LobbyManager
#define _Included_de_jcm_discordgamesdk_LobbyManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jcm_discordgamesdk_LobbyManager
 * Method:    getLobbyCreateTransaction
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_de_jcm_discordgamesdk_LobbyManager_getLobbyCreateTransaction
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jcm_discordgamesdk_LobbyManager
 * Method:    createLobby
 * Signature: (JJLjava/util/function/BiConsumer;)V
 */
JNIEXPORT void JNICALL Java_de_jcm_discordgamesdk_LobbyManager_createLobby
  (JNIEnv *, jobject, jlong, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
