/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jcm_discordgamesdk_Core */

#ifndef _Included_de_jcm_discordgamesdk_Core
#define _Included_de_jcm_discordgamesdk_Core
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jcm_discordgamesdk_Core
 * Method:    initDiscordNative
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_jcm_discordgamesdk_Core_initDiscordNative
  (JNIEnv *, jclass, jstring);

/*
 * Class:     de_jcm_discordgamesdk_Core
 * Method:    create
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_jcm_discordgamesdk_Core_create
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jcm_discordgamesdk_Core
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_jcm_discordgamesdk_Core_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jcm_discordgamesdk_Core
 * Method:    getActivityManager
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_jcm_discordgamesdk_Core_getActivityManager
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jcm_discordgamesdk_Core
 * Method:    runCallbacks
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_jcm_discordgamesdk_Core_runCallbacks
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
