/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jcm_discordgamesdk_OverlayManager */

#ifndef _Included_de_jcm_discordgamesdk_OverlayManager
#define _Included_de_jcm_discordgamesdk_OverlayManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jcm_discordgamesdk_OverlayManager
 * Method:    isEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_de_jcm_discordgamesdk_OverlayManager_isEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jcm_discordgamesdk_OverlayManager
 * Method:    isLocked
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_de_jcm_discordgamesdk_OverlayManager_isLocked
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jcm_discordgamesdk_OverlayManager
 * Method:    setLocked
 * Signature: (JZLjava/util/function/Consumer;)V
 */
JNIEXPORT void JNICALL Java_de_jcm_discordgamesdk_OverlayManager_setLocked
  (JNIEnv *, jobject, jlong, jboolean, jobject);

/*
 * Class:     de_jcm_discordgamesdk_OverlayManager
 * Method:    openActivityInvite
 * Signature: (JILjava/util/function/Consumer;)V
 */
JNIEXPORT void JNICALL Java_de_jcm_discordgamesdk_OverlayManager_openActivityInvite
  (JNIEnv *, jobject, jlong, jint, jobject);

/*
 * Class:     de_jcm_discordgamesdk_OverlayManager
 * Method:    openGuildInvite
 * Signature: (JLjava/lang/String;Ljava/util/function/Consumer;)V
 */
JNIEXPORT void JNICALL Java_de_jcm_discordgamesdk_OverlayManager_openGuildInvite
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     de_jcm_discordgamesdk_OverlayManager
 * Method:    openVoiceSettings
 * Signature: (JLjava/util/function/Consumer;)V
 */
JNIEXPORT void JNICALL Java_de_jcm_discordgamesdk_OverlayManager_openVoiceSettings
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
